[package]
name = "sc-rdl-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
config = "0.15.4"
dotenv = "0.15.0"
reqwest = { version = "0.12.12", features = ["json", "blocking"] }
rusqlite = "0.32.1"
serde = "1.0.217"
serde_json = "1.0.134"
tokio = "1.42.0"
