# sc-rdl Config file 
debug_level = "debug" # lowercase string, one of "debug", "info", "warn", "error", "trace", "off"

[spic]

login = "kgm@redlineekb.ru"
password = "5Amxqv"

[database]

db_type = "sqlite"

[database.sqlite]

path = "data/rdl.db"
log_path = "data/rdl.db"
pool_acquire_timeout = 10
pool_idle_timeout = 3600
minimum_connection_pool_size = 3
maximum_connection_pool_size = 20
pool_max_lifetime = 43200


[server]

address = "127.0.0.1"
port = "4339"
request_timeout = 5000