# sc-rdl Config file 
debug = true

[spic]

login = "kgm@redlineekb.ru"
password = "5Amxqv"

[database]

db_type = "sqlite"

[database.sqlite]

name = "rdl.db"
timeout = 5000
maximum_connection_pool_size = 5


[server]

address = "127.0.0.1"
port = "4339"
request_timeout = 5000